manifest:
  remotes:
    - name: esyo-net-zmkfirmware
      url-base: https://github.com/esyo-net
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
